name: kapt
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.16.0
  - certifi=2024.8.30
  - expat=2.7.3
  - fontconfig=2.14.2
  - freetype=2.12.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - icu=58.2
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libdeflate=1.10
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.80.2
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.43
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.3.0
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.2.13
  - ncurses=6.5
  - nomkl=1.0
  - numexpr=2.8.3
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=3.6.0
  - pcre2=10.43
  - pip=22.3.1
  - pixman=0.38.0
  - pthread-stubs=0.3
  - pycairo=1.21.0
  - python=3.7.12
  - python_abi=3.7
  - rdkit=2018.09.3
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.38.4
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - charset-normalizer==3.4.4
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - descriptastorus==2.6.1
      - fonttools==4.38.0
      - future==1.0.0
      - gensim==4.2.0
      - hyperopt==0.2.7
      - idna==3.10
      - importlib-metadata==6.7.0
      - jinja2==3.1.6
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - networkx==2.6.3
      - nltk==3.4.5
      - numpy==1.20.3
      - owlready2==0.37
      - packaging==24.0
      - pandas==1.3.5
      - pandas-flavor==0.7.0
      - pillow==9.5.0
      - protobuf==3.20.3
      - psutil==7.2.1
      - py4j==0.10.9.9
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit-pypi==2022.9.5
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - six==1.17.0
      - smart-open==7.1.0
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - torch==1.13.1+cu117
      - torch-cluster==1.6.1+pt113cu117
      - torch-geometric==2.3.1
      - torch-scatter==2.1.1+pt113cu117
      - torch-sparse==0.6.17+pt113cu117
      - torch-spline-conv==1.2.2+pt113cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - unidecode==1.4.0
      - urllib3==2.0.7
      - wrapt==1.16.0
      - xarray==0.20.2
      - zipp==3.15.0
